# Базовые понятия статистики 

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_list = []

In [3]:
with open ('/Users/maksim/Desktop/supreme-memory/практика_и_дз/horse_data.csv', 'r') as file:
    for horse in file:
        df_list.append(horse.split(','))

In [4]:
np.array(df_list)

array([['2', '1', '530101', ..., '00000', '00000', '2\n'],
       ['1', '1', '534817', ..., '00000', '00000', '2\n'],
       ['2', '1', '530334', ..., '00000', '00000', '1\n'],
       ...,
       ['1', '1', '529386', ..., '00000', '00000', '2\n'],
       ['1', '1', '530612', ..., '00000', '00000', '1\n'],
       ['1', '1', '534618', ..., '00000', '00000', '2']], dtype='<U7')

In [5]:
df = pd.DataFrame(np.array(df_list))
df.columns = ['surgery?', 'Age', 'Hospital Number', 'rectal temperature', 'pulse', 'respiratory rate', 
                'temperature of extremities', 'peripheral pulse', 'mucous membranes', 'capillary refill time', 
               'pain', 'peristalsis', 'abdominal distension', 'nasogastric tube', 'nasogastric reflux', 
               'nasogastric reflux PH', 'rectal examination - feces', 'abdomen', 'packed cell volume',
               'total protein', 'abdominocentesis appearance', 'abdomcentesis total protein', 'outcome', 
                'surgical lesion?', 'first number is site of lesion', 'second number is type', 'third number is subtype',
               'cp_data']

### Операции

In [6]:
df['surgery?'].unique()

array(['2', '1', '?'], dtype=object)

In [7]:
df['surgery?'].mode()[0]

'1'

In [8]:
df[df['surgery?'] == '?']

#Так как у нас пропущенно только одно значение. На основе предположения, что владельцу выгоднее 
#не сообщать о том, была ли операция у лошади и моды имеющихся значений  будем заменять это значение на '1'.

surgery? Age Hospital Number rectal temperature pulse respiratory rate  \
132        ?   1          534572               38.0    48               20   

    temperature of extremities peripheral pulse mucous membranes  \
132                          3                1                3   

    capillary refill time  ... packed cell volume total protein  \
132                     1  ...                 43            73   

    abdominocentesis appearance abdomcentesis total protein outcome  \
132                           2                           1       ?   

    surgical lesion? first number is site of lesion second number is type  \
132                1                          03111                 00000   

    third number is subtype cp_data  
132                   00000     2\n  

[1 rows x 28 columns]

In [9]:
df['surgery?'][df['surgery?'] == '?'] = '1'
df['surgery?'].unique()

array(['2', '1'], dtype=object)

### Возраст

In [10]:
df['Age'].unique()

# Согласно документации, для возраста характерны значения "1", "2", поэтому все "9" заменим на "2"

array(['1', '9'], dtype=object)

In [11]:
df['Age'][df['Age'] == '9'] = '2'
df['Age'].unique()

array(['1', '2'], dtype=object)

### Hospital Number

In [12]:
df['Hospital Number'].unique()

# Странных значений нет

array(['530101', '534817', '530334', '5290409', '530255', '528355',
       '526802', '529607', '530051', '5299629', '528548', '527927',
       '528031', '5291329', '534917', '530233', '5301219', '526639',
       '5290481', '532110', '530157', '529340', '521681', '534998',
       '533692', '529518', '530526', '528653', '5279442', '535415',
       '529475', '530242', '529427', '529663', '529796', '528812',
       '529493', '533847', '528996', '5277409', '529498', '5288249',
       '530301', '534069', '535407', '529827', '529888', '529821',
       '528890', '529642', '529766', '527706', '529483', '530544',
       '529461', '5282839', '528872', '529640', '528298', '528904',
       '530438', '527957', '528630', '534293', '529667', '534885',
       '534784', '528931', '529777', '530276', '528214', '529424',
       '5299253', '528469', '5292929', '534092', '534615', '534753',
       '530693', '527463', '527518', '534756', '5290759', '5279822',
       '529849', '529304', '529388', '528006', '5

### rectal temperature

In [13]:
df['rectal temperature'].unique()

array(['38.50', '39.2', '38.30', '39.10', '37.30', '?', '37.90', '38.10',
       '37.20', '38.00', '38.2', '37.60', '37.50', '39.4', '39.90',
       '38.40', '38.60', '38.3', '38.1', '37.80', '37.7', '37.70',
       '38.20', '37.8', '39.20', '39.00', '35.4', '38.90', '37.40',
       '40.30', '37.9', '37.00', '39.7', '37.6', '38.7', '36.40', '37.3',
       '38.0', '38.80', '39.60', '36.80', '38.4', '39.50', '36.5',
       '39.40', '38.70', '37.4', '38', '36.00', '37.1', '38.9', '39.30',
       '38.8', '39.5', '37.5', '38.5', '37.10', '36.10', '39.3', '36.60',
       '40.80', '36.90', '38.6', '40.00', '36.50', '37.2'], dtype=object)

In [14]:
df['rectal temperature'][df['rectal temperature'] == '?'] = np.nan

In [15]:
df['rectal temperature'].mode()

0    38.00
dtype: object

In [16]:
df['rectal temperature'].fillna(df['rectal temperature'].mode()[0], inplace = True)

In [17]:
df['rectal temperature'].unique()

array(['38.50', '39.2', '38.30', '39.10', '37.30', '38.00', '37.90',
       '38.10', '37.20', '38.2', '37.60', '37.50', '39.4', '39.90',
       '38.40', '38.60', '38.3', '38.1', '37.80', '37.7', '37.70',
       '38.20', '37.8', '39.20', '39.00', '35.4', '38.90', '37.40',
       '40.30', '37.9', '37.00', '39.7', '37.6', '38.7', '36.40', '37.3',
       '38.0', '38.80', '39.60', '36.80', '38.4', '39.50', '36.5',
       '39.40', '38.70', '37.4', '38', '36.00', '37.1', '38.9', '39.30',
       '38.8', '39.5', '37.5', '38.5', '37.10', '36.10', '39.3', '36.60',
       '40.80', '36.90', '38.6', '40.00', '36.50', '37.2'], dtype=object)

### pulse

In [18]:
df['pulse'].unique()

array(['66', '88', '40', '164', '104', '?', '48', '60', '80', '90', '72',
       '42', '92', '76', '96', '128', '64', '110', '130', '108', '100',
       '112', '52', '146', '150', '120', '140', '84', '46', '114', '160',
       '54', '56', '38', '98', '50', '44', '70', '78', '49', '30', '136',
       '132', '65', '86', '129', '68', '36', '45', '124', '184', '75',
       '82'], dtype=object)

In [19]:
df['pulse'][df['pulse'] == '?'] = np.nan

In [20]:
df['pulse'] = df['pulse'].astype('float64')

In [21]:
np.round(df.groupby('peripheral pulse')['pulse'].mean())

peripheral pulse
1    58.0
2    59.0
3    88.0
4    91.0
?    71.0
Name: pulse, dtype: float64

In [22]:
df['pulse'].fillna(np.round(df.groupby('peripheral pulse')['pulse'].transform('mean')), inplace = True)

In [23]:
df['pulse'].unique()

array([ 66.,  88.,  40., 164., 104.,  58.,  48.,  60.,  80.,  90.,  72.,
        42.,  92.,  76.,  96., 128.,  64., 110., 130.,  71., 108., 100.,
       112.,  52., 146., 150., 120., 140.,  84.,  46., 114., 160.,  54.,
        56.,  38.,  98.,  50.,  44.,  70.,  78.,  49.,  30., 136., 132.,
        65.,  86., 129.,  91.,  68.,  36.,  45., 124., 184.,  75.,  82.])

### respiratory rate

In [24]:
df['respiratory rate'].unique()

array(['28', '20', '24', '84', '35', '?', '16', '36', '12', '52', '48',
       '21', '60', '34', '42', '30', '96', '72', '15', '44', '32', '22',
       '18', '80', '40', '10', '51', '68', '66', '9', '14', '90', '8',
       '23', '58', '13', '70', '26', '88', '25', '50'], dtype=object)

In [27]:
df['respiratory rate'][df['respiratory rate'] == '?'] = np.nan
df['respiratory rate'] = df['respiratory rate'].astype('float64') 

<ipython-input-27-313f0816ff27>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['respiratory rate'][df['respiratory rate'] == '?'] = np.nan


In [28]:
df.groupby('Age')['respiratory rate'].transform('mean')

0      28.238739
1      28.238739
2      28.238739
3      54.600000
4      28.238739
         ...    
295    28.238739
296    28.238739
297    28.238739
298    28.238739
299    28.238739
Name: respiratory rate, Length: 300, dtype: float64

In [29]:
df['respiratory rate'].fillna(np.round(df.groupby('Age')['respiratory rate'].transform('mean')), inplace = True)

In [30]:
df['respiratory rate'].unique()

array([28., 20., 24., 84., 35., 16., 36., 55., 12., 52., 48., 21., 60.,
       34., 42., 30., 96., 72., 15., 44., 32., 22., 18., 80., 40., 10.,
       51., 68., 66.,  9., 14., 90.,  8., 23., 58., 13., 70., 26., 88.,
       25., 50.])

### outcome

In [31]:
df['outcome'].unique()

array(['2', '3', '1', '?'], dtype=object)

In [32]:
df['outcome'].mode()[0]

'1'

In [33]:
df['outcome'].value_counts()

1    178
2     77
3     44
?      1
Name: outcome, dtype: int64

In [34]:
df['outcome'][df['outcome'] == '?'] = '1'
df['outcome'].unique()

<ipython-input-34-c7e271e559e5>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['outcome'][df['outcome'] == '?'] = '1'


array(['2', '3', '1'], dtype=object)

### total protein

In [36]:
df['total protein'].unique()

array(['8.40', '85', '6.70', '7.20', '7.40', '?', '7.00', '8.30', '6.20',
       '6.00', '7.80', '6.10', '81', '6.80', '8.7', '70', '65', '5.50',
       '76', '7.50', '8.20', '6.60', '8.60', '80', '6.50', '8.50', '67',
       '69', '9.10', '7.70', '6.40', '8.10', '5.90', '8.00', '82', '72',
       '74', '6.30', '7.60', '4.90', '57', '68', '77', '8.90', '5.70',
       '4.50', '61', '86', '60', '66', '5.30', '7.30', '64', '58', '56',
       '75', '10.2', '62', '7.90', '73', '71', '7.0', '63', '46', '7.2',
       '5.80', '53', '4.70', '59', '55', '8.70', '89', '51', '4.00',
       '11.00', '8.80', '50', '54', '6.90', '4.60', '13', '7.10', '3.30',
       '9.00', '5.00'], dtype=object)

In [45]:
df['total protein'][df['total protein'] == '?'] = np.nan
df['total protein'] = df['total protein'].astype('float64')
df['total protein'].unique()

<ipython-input-45-1907a8a4f685>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total protein'][df['total protein'] == '?'] = np.nan


array([ 8.4, 85. ,  6.7,  7.2,  7.4,  nan,  7. ,  8.3,  6.2,  6. ,  7.8,
        6.1, 81. ,  6.8,  8.7, 70. , 65. ,  5.5, 76. ,  7.5,  8.2,  6.6,
        8.6, 80. ,  6.5,  8.5, 67. , 69. ,  9.1,  7.7,  6.4,  8.1,  5.9,
        8. , 82. , 72. , 74. ,  6.3,  7.6,  4.9, 57. , 68. , 77. ,  8.9,
        5.7,  4.5, 61. , 86. , 60. , 66. ,  5.3,  7.3, 64. , 58. , 56. ,
       75. , 10.2, 62. ,  7.9, 73. , 71. , 63. , 46. ,  5.8, 53. ,  4.7,
       59. , 55. , 89. , 51. ,  4. , 11. ,  8.8, 50. , 54. ,  6.9,  4.6,
       13. ,  7.1,  3.3,  9. ,  5. ])

In [44]:
df.groupby('Age')['total protein'].mean()

Age
1    25.437959
2    13.531818
Name: total protein, dtype: float64

In [47]:
df['total protein'].fillna(np.round(df.groupby('Age')['total protein'].transform('mean')), inplace = True)

In [49]:
df['total protein'].value_counts()

25.0    31
6.5     15
7.0     15
7.5     13
6.6     11
        ..
59.0     1
53.0     1
46.0     1
63.0     1
85.0     1
Name: total protein, Length: 83, dtype: int64

## New DataFrame

In [52]:
data = df[['Hospital Number', 'Age', 'surgery?', 'rectal temperature', 'pulse', 
           'respiratory rate', 'total protein', 'outcome']]
data.head(20)

Hospital Number Age surgery? rectal temperature  pulse  respiratory rate  \
0           530101   1        2              38.50   66.0              28.0   
1           534817   1        1               39.2   88.0              20.0   
2           530334   1        2              38.30   40.0              24.0   
3          5290409   2        1              39.10  164.0              84.0   
4           530255   1        2              37.30  104.0              35.0   
5           528355   1        2              38.00   58.0              28.0   
6           526802   1        1              37.90   48.0              16.0   
7           529607   1        1              38.00   60.0              28.0   
8           530051   1        2              38.00   80.0              36.0   
9          5299629   2        2              38.30   90.0              55.0   
10          528548   1        1              38.10   66.0              12.0   
11          527927   1        2              39.10   72.0              52.0   
12          528031   1        1              37.20   42.0              12.0   
13         5291329   2        2              38.00   92.0              28.0   
14          534917   1        1               38.2   76.0              28.0   
15          530233   1        1              37.60   96.0              48.0   
16         5301219   2        1              38.00  128.0              36.0   
17          526639   1        2              37.50   48.0              24.0   
18         5290481   1        1              37.60   64.0              21.0   
19          532110   1        2               39.4  110.0              35.0   

    total protein outcome  
0             8.4       2  
1            85.0       3  
2             6.7       1  
3             7.2       2  
4             7.4       2  
5            25.0       1  
6             7.0       1  
7             8.3       2  
8             6.2       3  
9             6.2       1  
10            6.0       1  
11            7.8       1  
12            7.0       1  
13            6.1       2  
14           81.0       1  
15            6.8       2  
16            7.8       2  
17           25.0       1  
18            7.0       1  
19            8.7       1